# Generated by Django 5.0.2 on 2024-02-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_visits", "0003_auto_20211126_2136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purpose",
            name="name",
            field=models.CharField(
                choices=[("appointment", "appointment"), ("treatment", "treatment")],
                max_length=100,
                unique=True,
            ),
        ),
    ]
